---
base_url: https://www.banxico.org.mx/SieAPIRest/service/v1/series/
################################# GRUPO 1 (Output and Income) #################################
   # Indicador Global de la Actividad Económica (IGAE) - Series desestazionarizadas
SR17693: # Total
   transformation: 1
   stationary: 0
SR17696: # Primario
   transformation: 1
   stationary: 0
SR17699: # Secundario
   transformation: 1
   stationary: 0
SR17702: # Terciario
   transformation: 1
   stationary: 0

################################# GRUPO 2 (Labor Market) #################################

   # Tasas de desocupación
SL1: # Tasas de desocupación abierta en áreas urbanas Total Porcentaje con respecto a la PEA
   transformation: 1
   stationary: 0

################################# GRUPO 4 (Consumption, orders, inventories) #################################

# Encuesta mensual de coyuntura, inventarios, empleo y días laborados: Con relación al mes anterior sus inventarios de productos terminados
SR344: # Aumentaron 
   transformation: 1
   stationary: 0
SR345: # Se quedaron iguales
   transformation: 1
   stationary: 0

# Encuesta mensual de coyuntura, inventarios, empleo y días laborados: Indice de confianza de las empresas manufactureras
SR2140:
   transformation: 1
   stationary: 0
#Subindice del clima de los negocios 
SR2135:
   transformation: 1
   stationary: 0


################################# GRUPO 5 (Money and Credit) #################################

SF50739: # Finaciamiento al sector privado, empresas, credito de intermediarios financieros
   transformation: 1
   stationary: 0
SF50740: # Emision de instrumentos de deuda
   transformation: 1
   stationary: 0

SF50737: # Fincianciamento al sector privado, hogares, para vivienda
   transformation: 1
   stationary: 0

SF50736: # Fincianciamento al sector privado, hogares, para consumo
   transformation: 1
   stationary: 0

################################# GRUPO 6 (Interest and exchange rates) #################################

SF33229: # Bonos a tasa fija a 7 años Tasa de rendimiento promedio mensual, en por ciento anual
   transformation: 1
   stationary: 0
   
################################# GRUPO 7 (Prices) #################################
   # Mercancias y servicios finales
SP3: # Mercancías y servicios finales (Por destino y origen de la producción) Mercancías finales con petróleo
   transformation: 1
   stationary: 0
SP4: # Principales índices INPP mercancías excluyendo petróleo
   transformation: 1
   stationary: 0
SP10131: #Mercancías y servicios finales (Por destino y origen de la producción) INPP mercancías y servcios finales, con petróleo I. Sector económico primario con petróleo
   transformation: 1
   stationary: 0
SP77: # Mercancías y servicios finales (Por destino y origen de la producción) INPP mercancías y servcios finales, con petróleo II. Sector económico secundario
   transformation: 1
   stationary: 0
SP89: # Mercancías y servicios finales (Por destino y origen de la producción) INPP mercancías y servcios finales, con petróleo III. Sector económico terciario
   transformation: 1
   stationary: 0
 
   # Servicios intermedios
SP66488: # INPP mercancías y servicios intermedios I. Sector económico primario
   transformation: 1
   stationary: 0
SP66469: # INPP mercancías y servicios intermedios II. Sector económico secundario
   transformation: 1
   stationary: 0
SP66481: # INPP mercancías y servicios intermedios III. Sector económico terciario
   transformation: 1
   stationary: 0
 
   # Producción total
SP10133: # INPP producción total I. Sector Económico Primario con Petróleo
   transformation: 1
   stationary: 0
SP10136: # INPP producción total II. Sector económico secundario
   transformation: 1
   stationary: 0
SP10148: # INPP producción total III. Sector económico terciario
   transformation: 1
   stationary: 0


################################# GRUPO 8 (Stock Market) #################################


#######ERROR AL USAR X13###############
SL11137: # Salarios contractuales Revisiones salariales Incremento salarial otros sectores (%)
   transformation: 1
   stationary: 0
   sa: 0
   group: 2
   source: banxico
   
SL2829: # Salarios contractuales Revisiones salariales Incremento salarial empresas públicas (%)
   transformation: 1
   stationary: 0
   sa: 0
   group: 2
   source: banxico
SL5113: # Número de trabajadores empresas publicas 
   transformation: 1
   stationary: 0
   sa: 0
   group: 2
   source: banxico
   # Salarios mínimos
SL11298: # Salarios Mínimos General Pesos por día
   transformation: 1
   stationary: 0
   sa: 0
   group: 2
   source: banxico
SL11295: # Salarios Mínimos Zona Libre de la Frontera Norte Pesos por día
   transformation: 1
   stationary: 0
   sa: 0
   group: 2
   source: banxico
SF61745: # Tasa objetivo
   transformation: 1
   stationary: 0
   sa: 0
   group: 6
   source: banxico
SF3338: # Cetes 91 días Tasa de rendimiento promedio mensual, en por ciento anual
   transformation: 1
   stationary: 0
   sa: 0
   group: 6
   source: banxico
SF3270: # Cetes 182 días tasa de rendimiento Tasa de rendimiento promedio mensual, en por ciento anual
   transformation: 1
   stationary: 0
   sa: 0
   group: 6
   source: banxico
SF3367: # Cetes 364 días Tasa de rendimiento promedio mensual, en por ciento anual
   transformation: 1
   stationary: 0
   sa: 0
   group: 6
   source: banxico
SF17990: # Bonos a tasa fija a 3 años Tasa de rendimiento promedio mensual, en por ciento anual
   transformation: 1
   stationary: 0
   sa: 0
   group: 6
   source: banxico
SF18608: # Bonos a tasa fija a 5 años Tasa de rendimiento promedio mensual, en por ciento anual
   transformation: 1
   stationary: 0
   sa: 0
   group: 6
   source: banxico
SF30057: # Bonos a tasa fija a 10 años Tasa de rendimiento promedio mensual, en por ciento anual
   transformation: 1
   stationary: 0
   sa: 0
   group: 6
   source: banxico

...